config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

   root 'static_pages#home'
   resources :items
   resources :users
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   
   resources :basket_items, only: [:create, :index, :destroy] 
   
   get '/basket', to: 'basket_items#index'
   
   resources :quotes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    
    validates :name, presence: true, length: { maximum: 50 }
    validates :price, presence: true
    validate :integer?
    
    def integer?
        unless price.to_i.positive?
            errors.add(:price, "should be a valid number")
        end
    end
    
    def self.visible
        where(hidden: false)
    end
end

app/models/quote.rb
class Quote

  def self.search(movie)
    filter = MovieQuotes.new
    filter.by_year("#{movie}")
    
    filter.results.each do |m| 
      puts m["content"]
    end
    
  end
  
end

app/models/session.rb
class Session
    include ActiveModel::Model
    
    attr_accessor :username
    
    validates :username, presence: true
    validate :username_exist_in_database
    
   def username_exist_in_database
        unless User.find_by(username: username)
           errors.add(:username, "user doesn't exist")
        end
        
   end
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
    
  def index
    if session[:items_in_basket].nil?
      flash[:danger] = "Basket is empty."
      redirect_to root_url
    else
      @basket_items = Item.find(session[:items_in_basket])
      @basket_items ||= Array.new
    end
    
   
    
  end
    
  def create
    item_id = params[:item_id]
    @item = Item.find(item_id)
    @items_in_basket = session[:items_in_basket]
    @items_in_basket ||= Array.new
    @items_in_basket.push(@item.id)
    session[:items_in_basket] = @items_in_basket
    flash[:info] = "Item added to basket."
    
  end
    
  def destroy 
    reset_session
    flash[:danger] = "Basket empty."
    redirect_to root_url
  end
    
  
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.visible
        
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to @item
           # flash[:success] = "New item created."
        else
           # flash[:danger] = "Name can't be blank"
            render 'new'
        end
    end
    
    def show
       @item = find_item
    end
    
    def edit 
        @item = find_item
    end
    
    def update
        @item = find_item
        if @item.update_attributes(item_params)
            @item.save#it can update individually the params
            flash.now[:info] = "Item updated."
            redirect_to @item
        else
            flash.now[:danger] = "Invalid information."
            render 'edit'
        end
    end

    
    
    def hide
        @item = find_item
        @item.destroy
        redirect_to items_url
    end
    
    def delete 
       @item = find_item 
       @item.delete
        
    end


    private
        def item_params
            params.require(:item).permit(:name, :price, :hidden, :add_to_basket)
        end
        
        def find_item
           Item.visible.find(params[:id] ) 
        end
        
        def item_message # Why did this not work in the helper?
             "Price for the new item is #{@item.price}"
        end
    
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
   
  def index
    @quotes = Quote.search(params[:search])
  end
    
  
  private
  
  # def quote_param
  #   params.require(:search).permit(:search)
  # end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session_form = Session.new
   
  end

  def create
    # @item = Item.new(item_params)
    # params.require(:item).permit(:name, :price, :hidden)
    @session_form = Session.new(session_params)
    
    if @session_form.valid?
      # login
      # redirect to user page
      user = User.find_by(username: @session_form.username)
      log_in(user)
      redirect_to user
    else
      render 'new'
    end
  end
  
  private
  
  def session_params
    params.require(:session).permit(:username)
  end
  
end
 #@session = Session.new(User.find_by(username: params[:session][:username]))

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_param)
      if @user.save
        flash[:success] = "Yey, you signed up."
        log_in(@user)
        redirect_to @user
      else
        render 'new'
      end
    end
    
    def index
     
    end
    
    def show
       @user = User.find(params[:id])
    end

  private

    def user_param
      params.require(:user).permit(:username)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
    def empty_whole_basket
        
        
    end
end

app/helpers/items_helper.rb
module ItemsHelper
    
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/basket_items/index.html.erb
<h1>Basket</h1>
<%= "------------" %>
<br>
<table>
<% @basket_items.each do |basket_item| %>
      <% #basket_item.attributes.transform_keys!(&:to_sym)  %>
      
      <tr>
        <td> <%= basket_item.name %> </td> 
         <td> <%= '|' %> </td> 
        <td>£ <%= basket_item.price %> </td>
        
      </tr>
    <% end %>
    
  </table>
  <%#= delete_all %>
    <%= button_to 'Destroy', basket_item_path(@basket_items), method: :delete%>  
<br>
<%= "------------" %>

app/views/items/edit.html.erb
<h1>Edit</h1>

<%= form_for @item do |f|   %>
<% if f.object.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(f.object.errors.count, "error") %>.
        </div>
        <ul>
        <% f.object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>    
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12">

<table class = "table table-bordered">
  <tr>
    <th>ID</th>
    <th>Name</th> 
    <th>Price</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Hide</th>
    <th>Add</th>
  </tr>
  <% @items.each do |item| %>
      <tr>
        <td> <%= link_to item.id, item %> </td>
        <td> <%= item.name %> </td>
        <td> £ <%= item.price %> </td>
        <td> <%= link_to 'Edit', edit_item_path(item) %> </td>
        <td> <%= link_to 'Delete', item, method: :delete   %> </td>
        <td><%= link_to 'Hide', item, method: :hide %></td>
        <td> <%= link_to "Add to Basket", basket_items_path({item_id: item.id}), method: :post %> </td>
      </tr>
    <% end %>

 
</table>
  
    </div>
  </div>
</div>
  <!--<table>-->
 
  <!--<#% filter = MovieQuotes.new%>-->
  <!--<#% filter.by_year("2005")%>-->
  
  <!--<#% filter.results.each do |movie|%>-->
  <!--  </tr>-->
  <!--    <td><#%= movie["content"] %> / </td><td><%= movie["movie"]["title"] %></td>-->
  <!--  </tr>-->
  <!--<#%end%>-->
  
  <!--</table>-->
<%= link_to "New Items", new_item_path %>

app/views/items/new.html.erb
<h1> New item </h1>



<%= form_for @item do |f|   %>
    <%= render 'shared/error_messages', obj: @item %>    
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <%= f.submit "Create new item", class: "btn btn-primary" %>
<% end %>

app/views/items/show.html.erb
<dl>
    <dt>Name</dt>
    <dd><%= @item.name %></dd>
    
    <dt>Price</dt>
    <dd><%= @item.price %> </dd>
 </dl>
 
 
 <%= link_to 'Edit', edit_item_path(@item) %>
 <%= link_to 'Back', items_path, title: 'Back'%>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>
    Rails practice  
  </title>
  <head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Rails practice", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "Basket", "#" %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "SignUp", new_user_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/quotes/index.html.erb
<h3>Search quotes</h3>

    <%= form_tag(quotes_path, method: :get) do %>
      <%= text_field_tag :search, nil, :placeholder => "Search quote here" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
    <table>
      <% @quotes.each do |movie| %>
        </tr>
          <td><%= movie["content"] %></td>
        </tr>
      <%end%>
      </table>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(obj.errors.count, "error") %>.
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">

  <%= link_to "Items", items_path, class: "btn btn-lg btn-info" %>
  
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user, url: users_path) do |f| %>
      <%= render 'shared/error_messages', obj: @user %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> User <%=@user.id%> </h1>
<center><h3>username: <%= @user.username%></h3></center>